import React from 'react'
import RevealOnScroll from '../UI/RevealOnScroll'

function About() {
    const skills = [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Node.js",
        "Express",
        "MongoDB",
        "Python",
        "Django",
        "Tailwind CSS",
        "Bootstrap",
        "Git",
        "Java",
        "C++",
        "Firebase",
        "SQL",
        "REST APIs",
        "GraphQL",
        "Docker",
    ]
  return (
    <section id="about" className="min-h-screen font-mono flex items-center justify-center py-20">
        <div className="max-w-3xl mx-auto px-4 ">
            <RevealOnScroll>
            <h2 className="max-w-3xl text-4xl font-semibold mb-12 bg-gradient-to-r from-teal-500 to-indigo-600 bg-clip-text text-transparent text-center">About Me</h2>
            <div className="p-8 mb-6 rounded-xl border-white/10 border-2 hover:-translate-y-1 transition-all">
                <p className="text-gray-300 mb-5 text-xl">
                    I am a software engineer with a passion for building secure, interactive, and scalable software solutions. I have a strong foundation in computer science principles and a keen interest in exploring new technologies. My goal is to create innovative solutions that solve real-world problems and enhance user experiences.
                </p>
            </div>
            </RevealOnScroll>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <RevealOnScroll>
                <div className="rounded-xl p-6 hover:-translate-y-1 transition-all">
                    <h3 className="text-2xl text-center font-bold mb-8">👨🏻‍💻Skills</h3>
                    <div className="flex flex-wrap justify-center gap-2">
                        {skills.map((skill, index) => (
                            <span key={index} className="bg-blue-500/10 text-blue-400 py-1 px-3 rounded-full text-balance hover:bg-blue-500/20 hover:shadow-[9_2px_8px_rgba(59,130,22.46,0.2)] transition cursor-pointer">
                                {skill}
                            </span>
                        ))}
                    </div>
                </div>
                </RevealOnScroll>
                <RevealOnScroll>
                <div className="p-6 hover:-translate-y-1 transition-all rounded-xl">
                    <h3 className="text-2xl text-center font-bold mb-8">📚Education</h3>
                    <ul className="pl-5 list-disc text-gray-300 list-inside text-lg">
                        <li className="mb-2">
                            <strong><em>Bachelors of Applied Computer Science</em></strong> - Dalhousie University (2021 - 2025)
                        </li>
                        <li className="mb-2">
                            <strong><em>Diploma in Computer Engineering</em></strong> - VPMP Polytechnic (2018 - 2021)
                        </li> 
                    </ul>
                </div>
                </RevealOnScroll>
            </div>
            <RevealOnScroll>
            <div className="p-6 hover:-translate-y-1 transition-all rounded-xl">
            <h3 className="text-2xl text-center font-bold mb-8">💼Work Experience</h3>
            <ul className="pl-5 list-disc list-inside text-lg text-gray-300">
                <li className="list-none">
                    <strong className="text-blue-500"><em>Software Engineer - AI Trainer</em></strong> - Outlier (June 2025 - Present)
                    <ul className="pl-5 list-disc list-inside text-lg text-gray-300">
                        <li>Independently evaluate and critique code generated by AI in response to technical prompts, ensuring it adheres to industry best practices, security standards, and efficiency requirements suitable for large enterprise environments.</li>
                        <li>Make improvements and optimizations to AI-proposed solutions, ensuring that code is robust, accurate, and maintainable using front-end technologies such as React JS and Tailwind CSS, as well as back-end technologies including JavaScript, Node.js, and Java.</li>
                        <li>Author, test, and submit high-quality code samples that address a wide array of real-world programming challenges, directly influencing the training data used to refine AI model performance and reliability for critical enterprise applications.</li>
                        <li>Document and annotate all code submissions clearly, providing insightful feedback that highlights best practices and rationale behind design decisions for future AI learning.</li>
                        <li>Uphold a high standard of software engineering excellence, producing code and feedback that meets the expectations of Fortune 500 clients and supports their complex business needs.</li>
                        <li>Operate as a self-directed, individual contributor with accountability for quality output and timely delivery in a remote freelance capacity.</li>
                    </ul>
                </li>
                <li className="list-none">
                    <strong className="text-blue-500"><em>Data Validation Associate</em></strong> - Symcor Inc (Nov 2021 - Present)
                    <ul className="pl-5 list-disc list-inside text-lg text-gray-300">
                        <li>Ensured data integrity by diligently keying and validating financial data on Global Business Solution application with 95% accuracy.</li>
                        <li>Analyzed financial transactions to find potential gaps, frauds or issues and adjusted them to those who required special 
                        handling. </li>
                        <li>Through my knowledge and efficiency, I achieved 100% client satisfaction rate for 3 years in a row.</li>
                    </ul>
                </li>
                <li className="list-none">
                    <strong className="text-blue-500"><em>Software Developer Intern</em></strong> - BrainyBeams Technologies (Oct 2020-June 2021)
                    <ul className="pl-5 list-disc list-inside text-lg text-gray-300">
                        <li>Engineered a robust e-commerce platform, emphasizing intuitiveness and advanced features for online shopping.</li>
                        <li>Utilized Django to design and implement a user-friendly interface, optimizing user registration, login, and password reset 
                        processes to elevate the overall user experience.</li>
                        <li>Integrated a comprehensive product catalog, simplifying user navigation and enhancing the shopping experience, 
                        resulting in increased user satisfaction and higher conversion rates.</li>
                        <li><strong>Tech Stack: </strong>Python, Git, Jira, Django, SQLite.</li>
                    </ul>
                </li>       
            </ul>
            </div>
            </RevealOnScroll>
        </div>
    </section>
)}

export default About
